package co.uk.brookes;

/**
 * Author: Fantou Thomas
 * Date: 8/22/13
 */

public class Token {
    public int kind;    // token kind
    public int pos;     // token position in bytes in the source text (starting at 0)
    public int charPos; // token position in characters in the source text (starting at 0)
    public int col;     // token column (starting at 1)
    public int line;    // token line (starting at 1)
    public String val;  // token value
    public Token next;  // ML 2005-03-11 Peek tokens are kept in linked list

    public static final int  // token and char codes
            none        = 0,
            ident       = 1,
            identChar   = 201,
            number      = 2,
            digit       = 202,
            decimal     = 205,
            atsign      = 3,
            charVal     = 203,
            stringVal   = 204,
            type_		= 4,
            integer_	= 6,
            real_	    = 7,
            bool_		= 8,
            char_		= 9,
            string_		= 10,
            record_		= 11,
            of_			= 12,
            end_		= 15,
            list_		= 16,
            enumerate_	= 17,
            caste_		= 19,
            init_		= 20,
            body_		= 21,
            inherits_	= 22,
            observes_	= 23,
            all_		= 24,
            in_			= 25,
            var_		= 26,
            set_		= 28,
            state_		= 31,
            action_		= 32,
            affect_		= 35,
            begin_		= 36,
            join_		= 37,
            quit_		= 38,
            suspend_	= 39,
            resume_		= 40,
            create_		= 41,
            destroy_	= 42,
            loop_		= 43,
            while_		= 44,
            do_			= 45,
            repeat_		= 46,
            until_		= 47,
            for_		= 48,
            to_			= 49,
            by_			= 50,
            forall_		= 51,
            if_			= 52,
            then_		= 53,
            elseif_		= 54,
            else_		= 55,
            case_		= 56,
            with_		= 58,
            when_		= 59,
            exist_		= 60,
            and_		= 61,
            or_			= 62,
            xor_		= 63,
            not_        = 64,
            plus        = 100,
            minus       = 101,
            times       = 102,
            slash       = 103,
            rem         = 104,
            eqlSign     = 105,
            neq         = 106,
            lss         = 107,
            leq         = 108,
            gtr         = 109,
            geq         = 110,
            assign      = 111,
            semicolon   = 112,
            colon       = 113,
            comma       = 114,
            period      = 115,
            lpar        = 116,
            rpar        = 117,
            lbrack      = 118,
            rbrack      = 119,
            lbrace      = 120,
            rbrace      = 121,
            aslash      = 122,
            effect      = 123,
            apostr      = 124,
            quote       = 125,
            excl        = 126,
            concat      = 127,
            eof         = 128,
            true_       = 129,
            false_      = 130;
}
